version: "0.5"

processes:
  setup:
    command: "cabal run dev-local -- setup"

  cardano-testnet:
    command: "cabal run dev-local -- start-local-testnet"
    depends_on:
      setup:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        # NOTE: devnet-env is hardcoded here.
        # TODO: Add an endpoint in dev-local to health check testnet
        command: "[ -S ./devnet-env/socket/node1/sock ]"
      initial_delay_seconds: 1
      period_seconds: 1
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60

  populate:
    command: "cabal run dev-local -- populate"
    disabled: true

  script-reexecutor:
    command: "cabal run plutus-script-reexecutor -- --socket devnet-env/socket/node1/sock --testnet 42 --script-yaml local-config/scripts.yaml"
    disabled: true
