version: "0.5"

processes:
  setup:
    command: "cabal run dev-local -- setup"

  cardano-testnet:
    command: "cabal run dev-local -- start-local-testnet"
    depends_on:
      setup:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        # NOTE: devnet-env is hardcoded here.
        # TODO: Add an endpoint in dev-local to health check testnet
        command: "[ -S ./devnet-env/socket/node1/sock ]"
      initial_delay_seconds: 1
      period_seconds: 1
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60

  populate-trigger-test:
    command: "cabal run dev-local -- populate trigger-test"
    disabled: true

  populate-escrow:
    command: "cabal run dev-local -- populate escrow"
    disabled: true

  script-reexecutor:
    command: "cabal run plutus-script-reexecutor -- run --node-socket devnet-env/socket/node1/sock --testnet-magic 42 --script-yaml local-config/scripts.yaml"
    depends_on:
      cardano-testnet:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: 8080
        path: "/events/non-existant"
      initial_delay_seconds: 1
      period_seconds: 2
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 30

  script-websocket-output:
    command: "websocat --text ws://localhost:8080/events-ws/ threadedstdio: | jq -C --unbuffered"
    depends_on:
      script-reexecutor:
        condition: process_healthy

  script-websocket-executions:
    command: "websocat --text ws://localhost:8080/events-ws/?type=execution threadedstdio: | jq -C --unbuffered"
    depends_on:
      script-reexecutor:
        condition: process_healthy
